export const TIPS = [
  "Spaced Repetition (SRS) is most effective when you study a little bit every day.",
  "Kanji are often composed of smaller pieces called 'radicals' that hint at their meaning.",
  "The 'Heisig Method' focuses on creating imaginative stories for each kanji.",
  "Don't worry about perfect stroke order at first, focus on recognition.",
  "The Box System in KanjiLock helps you track which kanji you have fully mastered.",
  "You can toggle 'Sequential Order' in Settings if you prefer a fixed study path.",
  "Many kanji have multiple 'On' and 'Kun' readings depending on context.",
  "Learning vocabulary words alongside kanji makes the readings easier to remember.",
  "A 'Box' level of 4 means you are a true Master of those kanji!",
  "Try to visualize the kanji in your mind before looking at the answer.",
  "Consistent study for 10 minutes is better than a 2-hour session once a week.",
  "Writing kanji by hand can help reinforce your visual memory.",
  "The UnLock AI can answer your questions about grammar and kanji usage.",
  "Flashcards are great for quick reviews while you're on the go.",
  "Targets help you stay motivated by setting clear weekly or daily goals.",
  "The 'Sensei' button during a quiz provides a detailed breakdown of the kanji.",
  "KanjiLock uses a dark mode interface to reduce eye strain during long study sessions.",
  "Progressive Mode unlocks new boxes only after you've mastered the previous ones.",
  "Level 1 mastery means 'Apprentice', keep practicing to reach Level 4!",
  "Context is king: some kanji meanings change when paired with others.",
  "Use the 'Pricing' page to see all the premium features available to you.",
  "Don't get discouraged by mistakes; they are essential steps in learning.",
  "The session timer helps you build speed and automaticity in recognition.",
  "You can customize the 'Session Size' in your Settings to fit your schedule.",
  "Auto-dismissing answers can speed up your study sessions significantly.",
  "Vibration feedback can be toggled on or off in the Settings menu.",
  "Check your 'Stats' regularly to see your overall progress and growth.",
  "The 'Ranking' page lets you compare your mastery with other players.",
  "Try saying the readings out loud to engage your auditory memory.",
  "Radicals like 'Water' (氵) or 'Fire' (火) often appear on the left side.",
  "The kanji for 'Sun' (日) and 'Moon' (月) combine to form 'Bright' (明).",
  "Many modern Japanese words use Katakana for foreign loanwords.",
  "Kanji was originally brought to Japan from China over 1,500 years ago.",
  "There are over 2,000 'Joyo' kanji taught in Japanese schools.",
  "KanjiLock focuses on the most frequently used kanji to maximize your efficiency.",
  "The 'UnLock' AI uses advanced RAG technology to provide accurate explanations.",
  "Mastering the first 100 kanji is the hardest part; it gets easier from there!",
  "Use the 'Search' feature in the app to quickly find specific kanji details.",
  "Setting a specific time for study each day helps build a lasting habit.",
  "The 'Box Level' only increases when you perform well in a full session.",
  "Confirm your Level 3 mastery after 5 days to reach the final Level 4.",
  "A 'Perfect Session' (no mistakes) is required to advance to higher box levels.",
  "Fast answers earn you more points in the session scoring system.",
  "The progress bar at the top shows how close you are to finishing the session.",
  "You can logout and log back in from any device to keep your progress synced.",
  "The app works best on modern browsers with JavaScript enabled.",
  "Glassmorphism design helps keep the interface feel light and modern.",
  "Hovering over elements often reveals additional information or tips.",
  "Keep your player name consistent to ensure all your stats are tracked correctly.",
  "Enjoy the journey! Learning kanji is a marathon, not a sprint."
];
